### PR TITLE
First draft getting started

### PR DESCRIPTION
**Pull request by gfontorbe**

### CODE REVIEW

**Comment by dhuebner** [comment]
Thanks @gfontorbe !
 
Documentation might change when we add a yoeman generator, but anyway here some points I missed in the description:

> Modify package.json to add a build script and necessary dependencies

- Which step creates a package.json file? I don't have it after following previous steps  

> Define your model

- File name is missing

> Implement views

- Same here, file name is missing. Also `tsx` file extension is important

> Connect to a model source

- should create a file named model-source.ts

Run example:
Currently I see a bogus edges rendering.
Bildschirm­foto 2023-02-14 um 09 46 25

**Comment by dhuebner** [comment]
One more detail...
In TaskNodeView:
```ts
const width = 100;
const height = 100;
```

are not used

**Comment by dhuebner** [comment]
>  you should see the following diagram

I think it would be also nice to mention what can one do with this diagram: e.g. move nodes, zoom in/out use panning.


I also noticed another rendering issue when clicking on a edge. Looks like orphaned labels:
 
Bildschirm­foto 2023-02-14 um 10 12 42

**Comment by gfontorbe** [comment]
> Thanks @gfontorbe !
> 
> Documentation might change when we add a yoeman generator, but anyway here some points I missed in the description:
> 
> > Modify package.json to add a build script and necessary dependencies
> 
> * Which step creates a package.json file? I don't have it after following previous steps
> 
> > Define your model
> 
> * File name is missing
> 
> > Implement views
> 
> * Same here, file name is missing. Also `tsx` file extension is important
> 
> > Connect to a model source
> 
> * should create a file named model-source.ts
> 
> Run example: Currently I see a bogus edges rendering. Bildschirm­foto 2023-02-14 um 09 46 25

The CSS for the edges is missing in the documentation.

@dhuebner  Do you think a basic css file should be added by the generator as well?

**Comment by dhuebner** [comment]
> The CSS for the edges is missing in the documentation.
> 
> @dhuebner Do you think a basic css file should be added by the generator as well?

It depends on what else will be generated. However it looks like the default style for `.sprotty-edge` doesn't work correctly. I didn't looked in Sprotty code base, but maybe this is something we need to fix it in Sprotty itself.

**Comment by dhuebner** [comment]
@gfontorbe 
Very nice! 

One last remarks. In the description you write `view.tsx` and `model.ts` in code snippets it is plural `/views` and `/models`.
And the connection routing-points are still missing (Next to upper-left corner of the green node). 

Bildschirm­foto 2023-02-21 um 16 18 47

**Pull request closed without merging**
